import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

from PIL import Image
from PIL.PngImagePlugin import PngInfo


SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = SCRIPT_DIR.parent
RESOURCES_DIR = SKILL_ROOT / "resources"
DEFAULT_PLANTUML_JAR_URL = (
    "https://github.com/plantuml/plantuml/releases/download/"
    "v1.2026.2/plantuml-1.2026.2.jar"
)
DEFAULT_LATEST_RELEASE_API_URL = "https://api.github.com/repos/plantuml/plantuml/releases/latest"
DEFAULT_DESCRIPTION = "Generated by PlantUML Generator Skill"
DEFAULT_JAR_PATH = RESOURCES_DIR / "plantuml.jar"
DEFAULT_CACHE_STATE_NAME = "plantuml-cache.json"
DEFAULT_JAR_REFRESH_DAYS = 30
MIN_JAVA_MAJOR = 8
USER_AGENT = "plantuml-generator-skill/2.2"


def ensure_parent_dir(path):
    path.parent.mkdir(parents=True, exist_ok=True)


def utc_now():
    return datetime.now(timezone.utc)


def format_timestamp(value):
    return value.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def parse_timestamp(value):
    if not value:
        return None

    normalized = value[:-1] + "+00:00" if value.endswith("Z") else value
    try:
        return datetime.fromisoformat(normalized)
    except ValueError:
        return None


def resolve_cache_state_path(jar_path):
    return jar_path.with_name(DEFAULT_CACHE_STATE_NAME)


def read_cache_state(state_path):
    try:
        return json.loads(state_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except (OSError, json.JSONDecodeError):
        return {}


def write_cache_state(state_path, state):
    try:
        ensure_parent_dir(state_path)
        state_path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    except OSError as exc:
        print(f"Warning: Could not update PlantUML cache state at {state_path}: {exc}", file=sys.stderr)


def should_check_for_updates(state, refresh_days):
    if refresh_days <= 0:
        return False

    last_checked_at = parse_timestamp(state.get("last_checked_at"))
    if not last_checked_at:
        return True

    return utc_now() - last_checked_at >= timedelta(days=refresh_days)


def is_primary_plantuml_jar_name(name):
    lowered = name.lower()
    if not lowered.endswith(".jar"):
        return False

    if not lowered.startswith("plantuml"):
        return False

    for excluded in ("javadoc", "sources"):
        if excluded in lowered:
            return False

    return True


def discover_latest_release_jar():
    request = urllib.request.Request(
        DEFAULT_LATEST_RELEASE_API_URL,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": USER_AGENT,
        },
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)

    tag_name = str(payload.get("tag_name") or "").strip()
    version = tag_name[1:] if tag_name.startswith("v") else tag_name
    assets = payload.get("assets") or []

    preferred_name = f"plantuml-{version}.jar" if version else ""
    chosen_asset = None

    if preferred_name:
        for asset in assets:
            if asset.get("name") == preferred_name:
                chosen_asset = asset
                break

    if not chosen_asset:
        candidates = [asset for asset in assets if is_primary_plantuml_jar_name(asset.get("name", ""))]
        candidates.sort(key=lambda asset: len(asset.get("name", "")))
        if candidates:
            chosen_asset = candidates[0]

    if not chosen_asset:
        raise RuntimeError("GitHub latest release metadata did not include a PlantUML jar asset.")

    download_url = chosen_asset.get("browser_download_url")
    if not download_url:
        raise RuntimeError("GitHub latest release metadata did not include a browser download URL.")

    return {
        "asset_name": chosen_asset.get("name"),
        "download_url": download_url,
        "tag_name": tag_name or None,
    }


def parse_java_major_version(version_output):
    version_match = re.search(r'version "([^"]+)"', version_output)
    if version_match:
        version_str = version_match.group(1)
    else:
        fallback_match = re.search(r"\b(?:openjdk|java)\s+(\d+(?:\.\d+)*)\b", version_output)
        if not fallback_match:
            return None
        version_str = fallback_match.group(1)

    if version_str.startswith("1."):
        parts = version_str.split(".")
        if len(parts) > 1 and parts[1].isdigit():
            return int(parts[1])
        return None

    major_match = re.match(r"(\d+)", version_str)
    if not major_match:
        return None

    return int(major_match.group(1))


def build_java_install_hint():
    if sys.platform == "darwin":
        return (
            "Install Java 8+ and try again. On macOS, a common option is "
            "`brew install --cask temurin`."
        )

    if sys.platform.startswith("linux"):
        return (
            "Install Java 8+ and try again. On Debian or Ubuntu, a common option is "
            "`sudo apt-get install openjdk-17-jre`."
        )

    if os.name == "nt":
        return (
            "Install Java 8+ and try again. On Windows, install a current JRE/JDK such as "
            "Eclipse Temurin and ensure `java` is on PATH."
        )

    return "Install Java 8+ and ensure a compatible `java` executable is available."


def first_non_empty_line(text):
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def probe_java_command(java_cmd):
    try:
        result = subprocess.run(
            [java_cmd, "-version"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
    except OSError as exc:
        return None, f"Could not execute `{java_cmd} -version`: {exc}"

    combined_output = "\n".join(
        part for part in [result.stdout.strip(), result.stderr.strip()] if part
    ).strip()

    if result.returncode != 0:
        return None, f"`{java_cmd} -version` failed: {combined_output or 'no output'}"

    major_version = parse_java_major_version(combined_output)
    if major_version is None:
        return None, f"Could not parse the Java version from: {combined_output or 'no output'}"

    if major_version < MIN_JAVA_MAJOR:
        return None, (
            f"`{java_cmd}` is Java {major_version}, but PlantUML requires Java "
            f"{MIN_JAVA_MAJOR}+."
        )

    return {
        "cmd": java_cmd,
        "major_version": major_version,
        "version_line": first_non_empty_line(combined_output),
    }, None


def macos_java_home_candidate():
    if sys.platform != "darwin":
        return None

    java_home_tool = Path("/usr/libexec/java_home")
    if not java_home_tool.exists():
        return None

    result = subprocess.run(
        [str(java_home_tool), "-v", "1.8+"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return None

    java_home = result.stdout.strip()
    if not java_home:
        return None

    candidate = Path(java_home) / "bin" / "java"
    if not candidate.exists():
        return None

    return str(candidate)


def candidate_java_commands(args):
    candidates = [
        args.java_cmd,
        os.environ.get("PLANTUML_JAVA_CMD"),
    ]

    java_home = os.environ.get("JAVA_HOME")
    if java_home:
        candidates.append(str(Path(java_home).expanduser() / "bin" / "java"))

    path_java = shutil.which("java")
    if path_java:
        candidates.append(path_java)

    candidates.append(macos_java_home_candidate())

    seen = set()
    for candidate in candidates:
        if not candidate:
            continue
        normalized = str(Path(candidate).expanduser()) if os.path.sep in candidate else candidate
        if normalized in seen:
            continue
        seen.add(normalized)
        yield normalized


def resolve_java_runtime(args):
    failures = []

    for candidate in candidate_java_commands(args):
        runtime, error = probe_java_command(candidate)
        if runtime:
            return runtime
        if error:
            failures.append(error)

    details = " ".join(failures[:3]) if failures else "No compatible Java runtime was found."
    raise RuntimeError(
        f"Java {MIN_JAVA_MAJOR}+ is required for PlantUML generate/update. "
        f"{details} Set `PLANTUML_JAVA_CMD` or `JAVA_HOME` to a compatible runtime. "
        f"{build_java_install_hint()}"
    )


def download_jar(jar_path, jar_url=None):
    ensure_parent_dir(jar_path)
    resolved_url = jar_url or DEFAULT_PLANTUML_JAR_URL
    print(f"Downloading PlantUML jar from {resolved_url}")

    fd, temp_name = tempfile.mkstemp(
        prefix="plantuml-download-",
        suffix=".jar",
        dir=str(jar_path.parent),
    )
    os.close(fd)
    temp_path = Path(temp_name)

    try:
        request = urllib.request.Request(
            resolved_url,
            headers={"User-Agent": USER_AGENT},
        )
        with urllib.request.urlopen(request, timeout=120) as response:
            final_url = response.geturl()
            with temp_path.open("wb") as file_obj:
                shutil.copyfileobj(response, file_obj)

        if temp_path.stat().st_size == 0:
            raise RuntimeError("Downloaded PlantUML jar is empty.")

        temp_path.replace(jar_path)
        print(f"Saved PlantUML jar to {jar_path}")
        return {
            "download_url": final_url,
            "downloaded_at": format_timestamp(utc_now()),
            "requested_url": resolved_url,
        }
    finally:
        if temp_path.exists():
            temp_path.unlink()


def resolve_jar_path(args):
    if args.jar_path:
        return Path(args.jar_path).expanduser().resolve()

    env_path = os.environ.get("PLANTUML_JAR_PATH")
    if env_path:
        return Path(env_path).expanduser().resolve()

    return DEFAULT_JAR_PATH.resolve()


def resolve_jar_url(args):
    return args.jar_url or os.environ.get("PLANTUML_JAR_URL") or DEFAULT_PLANTUML_JAR_URL


def jar_url_is_overridden(args):
    return bool(args.jar_url or os.environ.get("PLANTUML_JAR_URL"))


def resolve_refresh_days(args):
    raw_value = args.refresh_days
    if raw_value is None:
        raw_value = os.environ.get("PLANTUML_JAR_REFRESH_DAYS")

    if raw_value is None:
        return DEFAULT_JAR_REFRESH_DAYS

    try:
        refresh_days = int(raw_value)
    except ValueError as exc:
        raise RuntimeError(
            "PlantUML jar refresh interval must be an integer number of days. "
            "Use --refresh-days or PLANTUML_JAR_REFRESH_DAYS."
        ) from exc

    if refresh_days < 0:
        raise RuntimeError("PlantUML jar refresh interval must be 0 or greater.")

    return refresh_days


def refresh_cached_jar_if_due(jar_path, jar_url, refresh_days, enable_release_checks):
    state_path = resolve_cache_state_path(jar_path)
    state = read_cache_state(state_path)

    if not should_check_for_updates(state, refresh_days):
        return

    now = format_timestamp(utc_now())

    if not enable_release_checks:
        state["download_url"] = state.get("download_url") or jar_url
        state["last_checked_at"] = now
        write_cache_state(state_path, state)
        return

    print(f"Checking for PlantUML updates (every {refresh_days} days)...")

    try:
        latest_release = discover_latest_release_jar()
        current_download_url = state.get("download_url") or jar_url or DEFAULT_PLANTUML_JAR_URL

        if latest_release["download_url"] != current_download_url:
            print(
                "A newer PlantUML release is available. "
                f"Refreshing cached jar to {latest_release.get('tag_name') or latest_release.get('asset_name')}..."
            )
            download_result = download_jar(jar_path, jar_url=latest_release["download_url"])
            state.update(download_result)
            if latest_release.get("asset_name"):
                state["asset_name"] = latest_release["asset_name"]
            if latest_release.get("tag_name"):
                state["tag_name"] = latest_release["tag_name"]
        else:
            print("PlantUML jar cache is already current.")
            state["download_url"] = current_download_url
            if latest_release.get("asset_name"):
                state["asset_name"] = latest_release["asset_name"]
            if latest_release.get("tag_name"):
                state["tag_name"] = latest_release["tag_name"]
    except (urllib.error.URLError, TimeoutError, RuntimeError, json.JSONDecodeError) as exc:
        print(
            "Warning: Could not check for PlantUML updates. "
            f"Continuing with cached jar at {jar_path}. Original error: {exc}",
            file=sys.stderr,
        )
    finally:
        state["last_checked_at"] = now
        write_cache_state(state_path, state)


def ensure_jar_available(
    jar_path,
    jar_url=None,
    allow_download=True,
    refresh_days=DEFAULT_JAR_REFRESH_DAYS,
    enable_release_checks=True,
):
    state_path = resolve_cache_state_path(jar_path)
    state = read_cache_state(state_path)

    if jar_path.exists():
        if allow_download:
            refresh_cached_jar_if_due(
                jar_path,
                jar_url=jar_url,
                refresh_days=refresh_days,
                enable_release_checks=enable_release_checks,
            )
        return jar_path

    if not allow_download:
        raise FileNotFoundError(
            f"PlantUML jar not found at {jar_path}. "
            "Provide --jar-path or rerun without --no-download."
        )

    print(f"PlantUML jar not found at {jar_path}. Bootstrapping it now...")
    try:
        download_result = download_jar(jar_path, jar_url=jar_url)
    except (urllib.error.URLError, TimeoutError, RuntimeError) as exc:
        raise RuntimeError(
            "Could not download the PlantUML jar automatically. "
            "Provide --jar-path, set PLANTUML_JAR_PATH, or override the URL with --jar-url. "
            f"Original error: {exc}"
        ) from exc

    state.update(download_result)
    state["last_checked_at"] = download_result["downloaded_at"]
    write_cache_state(state_path, state)
    return jar_path


def generate_plantuml(puml_file, output_png, jar_path, java_cmd):
    """Generate a PNG image from a PlantUML file using the configured Java runtime and jar."""
    try:
        puml_path = Path(puml_file).expanduser().resolve()
        output_path = Path(output_png).expanduser().resolve()
        ensure_parent_dir(output_path)

        if not puml_path.exists():
            print(f"Error: PlantUML source file not found: {puml_path}", file=sys.stderr)
            return False

        with puml_path.open("rb") as file_in:
            with output_path.open("wb") as file_out:
                result = subprocess.run(
                    [java_cmd, "-jar", str(jar_path), "-tpng", "-pipe"],
                    stdin=file_in,
                    stdout=file_out,
                    stderr=subprocess.PIPE,
                    check=False,
                )

        if result.returncode != 0:
            stderr_output = result.stderr.decode("utf-8", errors="replace").strip()
            print("PlantUML generation failed.", file=sys.stderr)
            if stderr_output:
                print(stderr_output, file=sys.stderr)
            return False

        if not output_path.exists() or output_path.stat().st_size == 0:
            print(
                f"Error: Output file {output_path} was not created or is empty.",
                file=sys.stderr,
            )
            return False

        return True
    except Exception as exc:
        print(
            f"An unexpected error occurred during generation: {exc}",
            file=sys.stderr,
        )
        return False


def build_png_metadata(existing_info, source_code):
    metadata = PngInfo()
    for key, value in existing_info.items():
        if isinstance(value, str) and key not in {"Source", "Description"}:
            metadata.add_text(key, value)

    metadata.add_text("Source", source_code)
    metadata.add_text("Description", DEFAULT_DESCRIPTION)
    return metadata


def embed_metadata(png_path, source_code):
    """Embed the PlantUML source code into the PNG metadata."""
    try:
        png_path = Path(png_path).expanduser().resolve()
        with Image.open(png_path) as source_image:
            rendered_image = source_image.copy()
            metadata = build_png_metadata(source_image.info, source_code)

        rendered_image.save(png_path, pnginfo=metadata)
        return True
    except Exception as exc:
        print(f"Error embedding metadata: {exc}", file=sys.stderr)
        return False


def extract_metadata(png_path):
    """Extract the PlantUML source code from the PNG metadata."""
    try:
        png_path = Path(png_path).expanduser().resolve()
        if not png_path.exists():
            print(f"Error: File not found: {png_path}", file=sys.stderr)
            return None

        with Image.open(png_path) as image:
            return image.info.get("Source")
    except Exception as exc:
        print(f"Error extracting metadata: {exc}", file=sys.stderr)
        return None


def read_source_file(path):
    return Path(path).expanduser().resolve().read_text(encoding="utf-8")


def write_text_file(path, content):
    path = Path(path).expanduser().resolve()
    ensure_parent_dir(path)
    path.write_text(content, encoding="utf-8")


def parse_args():
    parser = argparse.ArgumentParser(description="PlantUML Image Generator & Metadata Tool")
    parser.add_argument(
        "--jar-path",
        help="Override the PlantUML jar path. Defaults to PLANTUML_JAR_PATH or the skill resources cache.",
    )
    parser.add_argument(
        "--jar-url",
        help="Override the download URL used when the jar is missing. Defaults to the hard-coded GitHub PlantUML release URL.",
    )
    parser.add_argument(
        "--java-cmd",
        help="Override the Java executable. Defaults to PLANTUML_JAVA_CMD, JAVA_HOME/bin/java, PATH java, or macOS java_home.",
    )
    parser.add_argument(
        "--no-download",
        action="store_true",
        help="Fail instead of downloading the PlantUML jar when it is missing.",
    )
    parser.add_argument(
        "--refresh-days",
        help=(
            "Check GitHub for a newer PlantUML jar only after this many days. "
            "Defaults to PLANTUML_JAR_REFRESH_DAYS or 30. Use 7 for weekly checks, 30 for monthly, or 0 to disable."
        ),
    )

    subparsers = parser.add_subparsers(dest="command", help="Command to execute")

    gen_parser = subparsers.add_parser("generate", help="Generate PNG from .puml file")
    gen_parser.add_argument("puml_file", help="Path to the .puml source file")
    gen_parser.add_argument("output_png", nargs="?", help="Optional path for the output PNG")

    ext_parser = subparsers.add_parser("extract", help="Extract .puml source from PNG metadata")
    ext_parser.add_argument("png_file", help="Path to the PNG file")
    ext_parser.add_argument("-o", "--output", help="Optional path to save the extracted source")

    upd_parser = subparsers.add_parser(
        "update",
        help="Update a PNG from embedded metadata or a new source string",
    )
    upd_parser.add_argument("png_file", help="Path to the PNG file to update")
    upd_parser.add_argument("-s", "--source", help="Optional new PlantUML source string")

    return parser.parse_args()


def main():
    args = parse_args()

    if not args.command:
        print("Choose one of: generate, extract, update.", file=sys.stderr)
        return 1

    if args.command == "extract":
        source = extract_metadata(args.png_file)
        if not source:
            print("No PlantUML source found in metadata.", file=sys.stderr)
            return 1

        if args.output:
            write_text_file(args.output, source)
            print(f"Source code extracted and saved to {Path(args.output).expanduser().resolve()}")
            return 0

        print("--- PlantUML Source ---")
        print(source)
        print("--- End Source ---")
        return 0

    try:
        java_runtime = resolve_java_runtime(args)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1

    jar_path = resolve_jar_path(args)
    jar_url = resolve_jar_url(args)
    enable_release_checks = not jar_url_is_overridden(args)

    try:
        refresh_days = resolve_refresh_days(args)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1

    try:
        jar_path = ensure_jar_available(
            jar_path,
            jar_url=jar_url,
            allow_download=not args.no_download,
            refresh_days=refresh_days,
            enable_release_checks=enable_release_checks,
        )
    except (FileNotFoundError, RuntimeError) as exc:
        print(exc, file=sys.stderr)
        return 1

    if args.command == "generate":
        output_png = args.output_png or str(Path(args.puml_file).with_suffix(".png"))
        print(f"Using Java {java_runtime['major_version']}: {java_runtime['version_line']}")
        print(f"Generating diagram from {args.puml_file}...")
        if not generate_plantuml(args.puml_file, output_png, jar_path, java_runtime["cmd"]):
            return 1

        source_code = read_source_file(args.puml_file)
        if not embed_metadata(output_png, source_code):
            print("Failed to embed metadata.", file=sys.stderr)
            return 1

        print(f"Successfully generated and embedded metadata in {Path(output_png).expanduser().resolve()}")
        return 0

    if args.command == "update":
        source_code = args.source
        if not source_code:
            print(f"Extracting source from {args.png_file} for re-render...")
            source_code = extract_metadata(args.png_file)

        if not source_code:
            print("Error: No source provided and none found in PNG metadata.", file=sys.stderr)
            return 1

        if args.source:
            source_code = source_code.replace("\\n", "\n")

        temp_path = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                suffix=".puml",
                delete=False,
            ) as temp_file:
                temp_file.write(source_code)
                temp_path = Path(temp_file.name)

            print(f"Using Java {java_runtime['major_version']}: {java_runtime['version_line']}")
            print(f"Re-rendering diagram from source (length={len(source_code)})...")
            if not generate_plantuml(temp_path, args.png_file, jar_path, java_runtime["cmd"]):
                print("Update failed.", file=sys.stderr)
                return 1

            if not embed_metadata(args.png_file, source_code):
                print("Failed to embed metadata during update.", file=sys.stderr)
                return 1

            print(f"Successfully updated {Path(args.png_file).expanduser().resolve()}")
            return 0
        finally:
            if temp_path and temp_path.exists():
                temp_path.unlink()

    print(f"Unsupported command: {args.command}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
